### ISSUE TITLE
Support input4MIPs file naming convention.

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/libaccessom2#20]
We need to support the input4MIPS file naming convention as the JRA55-do dataset is being distributed through this channel. 

A full description is here:

https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit

But a representative example is the river runoff:

```ocean/day/friver/gn/v20180412/friver/friver_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-3_gn_19580101-19590101.nc```

So the `forcing.json` file will need (at a minimum) to specify some arithmetic, so `{{year+1}}`, and hard code the month and day, or also support `{{month}}` and `{{day}}`

**Comment by aidanheerdegen** [comment]
For the moment I have made a directory
```/g/data1/ua8/JRA55-do/input4MIPs```
with appropriately named symlinks to the input4MIPs data, like so:
```
$ ls -l rsds_1958.nc 
lrwxrwxrwx 1 aph502 ua8 186 Apr 12 14:41 rsds_1958.nc -> /g/data1b/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/rsds/gn/v20180412/rsds/rsds_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-3_gn_195801010130-195901010000.nc
```

**Comment by aidanheerdegen** [comment]
Unfortunately these transformed files use `lon` and `lat` variables and dimensions, which are not supported by libaccessom2 currently.

https://github.com/OceansAus/libaccessom2/blob/5ec57165fb132cc28ecba5344701a1bc3cbac10d/libcouple/src/util.F90#L131-L137

**Comment by aekiss** [comment]
oops, it seems I made a duplicate issue https://github.com/COSIMA/libaccessom2/issues/25 - can we move discussion there?

**Comment by aekiss** [comment]
discussion moved to https://github.com/COSIMA/libaccessom2/issues/25
