### ISSUE TITLE
use submodules for included libraries (oasis, json-fortran, datetime-fortran)?

### ISSUE THREAD

**Issue by aekiss** [COSIMA/libaccessom2#29]
I'm wondering why we don't incorporate these into the libaccessom2 repo as submodules?
https://github.com/COSIMA/oasis3-mct
https://github.com/jacobwilliams/json-fortran
https://github.com/nicjhan/datetime-fortran

At present these are git cloned by cmake (see `ExternalProject_Add` entries in [CMakeLists.txt](https://github.com/COSIMA/libaccessom2/blob/master/CMakeLists.txt#L58)) which seems unnecessarily obscure, as it means we don't see the full codebase until cmake is run. 

I'd prefer these to be submodules, so a `git clone --recursive` (either of libaccessom2 or access-om2) will deliver all the source code, with no cmake dependency.

The present arrangement makes it too easy to overlook these libraries when searching the codebase (e.g. https://github.com/COSIMA/libaccessom2/issues/24), especially if using an offline clone of the code (e.g. on my laptop, where I wouldn't normally run cmake).

**Comment by nichannah** [comment]
I think that the cmake approach is simpler than the git submodule approach (e.g. being able to see the repo url and hash without git commands). 

However since we already use submodules it is introducing more complexity and more stuff to know.

So I think we do this issue and then if we decide we don't like git submodules later then switch everything over to the cmake approach. i.e. just have one approach or the other not both.

**Comment by aekiss** [comment]
OK, sounds good

**Comment by nichannah** [comment]
This has been merged into libaccessom2/dev branch

**Comment by aekiss** [comment]
just noting here that this is commit https://github.com/COSIMA/libaccessom2/commit/794284b1dd093d24af8095e995809b356d7455f3
(the commit message had the wrong issue number)

**Comment by aekiss** [comment]
@nichannah this commit will change to a much newer version of [json-fortran](https://github.com/jacobwilliams/json-fortran/commits/master). That might be a good thing, or it might break things. If the latter, we should check out the specific commit we want.
https://github.com/COSIMA/libaccessom2/commit/794284b1dd093d24af8095e995809b356d7455f3#diff-8903239df476d7401cf9e76af0252622

**Comment by aekiss** [comment]
Perhaps we could use our own fork of `json-fortran` (as you've done with `oasis3-mct` and `datetime-fortran`) rather than referring directly to the originals? This doesn't really help with the version issue, but at least means we have a copy of the repo in case it is removed.

**Comment by aekiss** [comment]
It would be better to use https://github.com/COSIMA/datetime-fortran rather than https://github.com/nicjhan/datetime-fortran so more of us have edit access.

There have been a few minor-looking updates to https://github.com/wavebitscientific/datetime-fortran/commits/master - might be worth updating our fork?

**Comment by nichannah** [comment]
OK, good suggestions.

**Comment by nichannah** [comment]
This has been merged into dev
