### ISSUE TITLE
Yatm crashes on 20/1/1968

### ISSUE THREAD

**Issue by nichannah** [COSIMA/libaccessom2#3]
HI @nic good morning,  i am getting same error as you fixed for me before  like   WARNING from PE   183: set_date_c: Year zero is invalid. Resetting year to 1

WARNING from PE   183: set_date_c: Year zero is invalid. Resetting year to 1

forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source      
yatm_c2868e5b.exe  00000000006F8001  Unknown               Unknown  Unknown
yatm_c2868e5b.exe  00000000006F613B  Unknown               Unknown  Unknown.

Abhishek [12:20 PM]
Here is the last few lines,it seems like we have problem in 1968 field_update_data: index 0000000153
{ “checksum-matmxx-snow_ai-0001641600”: 0.7015145634E+000 }
forcing_update_field at 1968-01-20T00:00:00.000
field_update_data: file /g/data1/ua8/JRA55-do/v1-3/slp.1968.18Aug2017.nc
field_update_data: index 0000000153
{ “checksum-matmxx-press_ai-0001641600": 0.2070275826E+011 }
forcing_update_field at 1968-01-20T00:00:00.000

**Comment by nic** [comment]
Thanks to fix the error. :smiley:
