### ISSUE TITLE
support time-invariant forcing perturbations

### ISSUE THREAD

**Issue by aekiss** [COSIMA/libaccessom2#31]
It would be useful to have support time-invariant [additive](https://github.com/COSIMA/libaccessom2/issues/30) or [multiplicative](https://github.com/COSIMA/access-om2/wiki/Tutorials#Scaling-the-forcing-fields) perturbations, so we don't necessarily need to specify the perturbation at every forcing timestep. This would be particularly handy for the IAF runs.

This could be implemented by applying the perturbation at every time if the perturbation file is missing a time axis.

**Comment by russfiedler** [comment]
@aekiss  @nichannah   I've made a start on this. First step is just to apply a constant scaling. I've got this in `/scratch/v45/raf599/libaccessom2` . Just looks like a couple of changes to `libcouple/src/field.F90` and `atm/src/forcing.F90`. Could you have a quick look to see if it's the sort of change that looks interesting and if I'm going about it the right way.

**Comment by aekiss** [comment]
thanks @russfiedler that looks good to me, I only had a few minor comments

**Comment by aekiss** [comment]
closing - this use case is supported by the new perturbation feature - see https://github.com/COSIMA/libaccessom2/issues/30 and
https://github.com/COSIMA/access-om2/wiki/Tutorials#Scaling-the-forcing-fields
