### ISSUE TITLE
Forcing with daily coupled model output

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/libaccessom2#59]
Rishav is trying to force ACCESS-OM2 with daily output from the ACCESS-CM2 coupled model. At first he tried monthly but it gave this unhelpful error
```
assertion failed: accessom2_sync_config: total runtime in seconds not integer multiple of atm_ice_timestep
1
```
which suggests an error in the time steps, but this is a red herring.

He switched to daily forcing and it worked, but crashes at the end of the year with this error
```
 MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch 
 LocalMap Gsize =        27648  RemoteMap Gsize =       204800
MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3
 MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch 
 LocalMap Gsize =       204800  RemoteMap Gsize =        27648
MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3

Image              PC                Routine            Line        Source             
yatm_4198e150.exe  00000000007F57CA  Unknown               Unknown  Unknown
yatm_4198e150.exe  0000000000708E4C  Unknown               Unknown  Unknown
yatm_4198e150.exe  00000000007076E4  Unknown               Unknown  Unknown
yatm_4198e150.exe  0000000000709E39  Unknown               Unknown  Unknown
yatm_4198e150.exe  0000000000673538  Unknown               Unknown  Unknown
yatm_4198e150.exe  00000000005E958A  mod_oasis_coupler        1055  mod_oasis_coupler.F90
yatm_4198e150.exe  000000000049F454  mod_oasis_method_         741  mod_oasis_method.F90
yatm_4198e150.exe  00000000004461A1  coupler_mod_mp_co         149  coupler.F90
yatm_4198e150.exe  0000000000412A6B  MAIN__.V                  133  atm.F90
yatm_4198e150.exe  0000000000410D62  Unknown               Unknown  Unknown
libc-2.28.so       00001524A67696A3  __libc_start_main     Unknown  Unknown
yatm_4198e150.exe  0000000000410C6E  Unknown               Unknown  Unknown

```
which is eerily similar to an error encountered in the tests

https://github.com/COSIMA/libaccessom2/issues/36#issuecomment-642401800

His control directory is here `/scratch/e14/rg1653/access-om2/control/1deg_50years`

Any ideas @nichannah ?

**Comment by russfiedler** [comment]
That mismatch error often arises to a problem with the the river runoff remapping file. It gets read through `atm_nml` rather than the `namcouple` file. Check that it's pointing to the right file. I thought this would have been a problem at the start though. 

Edit: Umm, that traceback is definitely from the start of the run. Why do you think it's from the end of the year?

**Comment by aidanheerdegen** [comment]
Rishav has resubmitted and AFAICT it has crashed at a different location, i.e. the start. Now I am confused, and can't locate the previous crash log.

Thanks for the feedback @russfiedler I'll follow up with the new info.

**Comment by aidanheerdegen** [comment]
This issue was due to an incorrect time dimension in one of the forcing files. Closing.
